import os
import json
import hashlib
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

import requests
from bs4 import BeautifulSoup


SCHOLARSHIP_URL = "https://www.education.go.ug/scholarships/"
STATE_FILE = "seen_scholarships.json"

EMAIL_USERNAME = os.environ.get("EMAIL_USERNAME")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")
ALERT_EMAIL = os.environ.get("ALERT_EMAIL", "reaganpatrickl896@gmail.com")


def get_page():
    response = requests.get(
        SCHOLARSHIP_URL,
        timeout=30,
        headers={
            "User-Agent": "Mozilla/5.0 (compatible; MOE Scholarship Monitor/1.0)"
        },
    )
    response.raise_for_status()
    return response.text


def get_scholarships(html):
    soup = BeautifulSoup(html, "html.parser")

    results = []

    for link in soup.find_all("a", href=True):
        title = link.get_text(" ", strip=True)
        href = link["href"].strip()

        if not title:
            continue

        title_lower = title.lower()

        keywords = [
            "scholarship",
            "scholarships",
            "fellowship",
            "fellowships",
            "study",
            "studies",
            "training",
        ]

        if any(keyword in title_lower for keyword in keywords):
            if href.startswith("/"):
                href = "https://www.education.go.ug" + href

            results.append({
                "title": title,
                "url": href,
            })

    unique = {}

    for item in results:
        key = item["url"]
        unique[key] = item

    return list(unique.values())


def item_id(item):
    value = item["title"] + "|" + item["url"]
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def load_seen():
    if not os.path.exists(STATE_FILE):
        return set()

    try:
        with open(STATE_FILE, "r", encoding="utf-8") as file:
            return set(json.load(file))
    except Exception:
        return set()


def save_seen(seen):
    with open(STATE_FILE, "w", encoding="utf-8") as file:
        json.dump(sorted(seen), file, indent=2)


def send_email(new_items):
    if not EMAIL_USERNAME or not EMAIL_PASSWORD:
        raise RuntimeError(
            "EMAIL_USERNAME or EMAIL_PASSWORD GitHub Secret is missing."
        )

    subject = f"🎓 New Uganda Scholarship Alert ({len(new_items)})"

    body = """
New scholarship announcement detected on the Uganda Ministry of Education and Sports website.

"""

    for item in new_items:
        body += f"""
Scholarship:
{item["title"]}

Official link:
{item["url"]}

------------------------------
"""

    body += f"""
Source:
{SCHOLARSHIP_URL}

This notification was automatically generated by the MOE Scholarship Monitor.
"""

    message = MIMEMultipart()
    message["From"] = EMAIL_USERNAME
    message["To"] = ALERT_EMAIL
    message["Subject"] = subject

    message.attach(MIMEText(body, "plain", "utf-8"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(EMAIL_USERNAME, EMAIL_PASSWORD)
        server.send_message(message)


def main():
    print("Checking Uganda Ministry of Education scholarship page...")

    html = get_page()
    scholarships = get_scholarships(html)

    print(f"Found {len(scholarships)} scholarship-related entries.")

    seen = load_seen()

    new_items = []

    for item in scholarships:
        identifier = item_id(item)

        if identifier not in seen:
            new_items.append(item)
            seen.add(identifier)

    if not new_items:
        print("No new scholarships found.")
        save_seen(seen)
        return

    print(f"Found {len(new_items)} new scholarship entries.")

    send_email(new_items)

    save_seen(seen)

    print("Email notification sent successfully.")


if __name__ == "__main__":
    main()
